### ISSUE TITLE
 std::io::Read input

### ISSUE THREAD

**Issue by 89z** [xlc/lite-json#24]
If I have a reader input, for example coming from a HTTP request, can I JSON parse from the reader directly?

or do I have to read into a string first? It seems that for larger inputs, it could be more efficient to parse JSON from reader directly

**Comment by xlc** [comment]
It should be relatively easy to implement `Input` for std::io::Read (or a wrapper of it) to achieve the desired outcome.

https://github.com/xlc/lite-json/blob/2c12af4a8606ed3c0988a4b2e9169278df91c6f2/parser/src/traits.rs#L13

**Comment by 89z** [comment]
I found a workaround for now:

https://docs.rs/serde_json/latest/serde_json/fn.from_reader.html
