### ISSUE TITLE
How to fetch floating no in offchain worker?

### ISSUE THREAD

**Issue by Aideepakchaudhary** [xlc/lite-json#28]
I want to fetch the floating value in offchain worker. I'm using `lite_json` for http request.

``` json
Api data: {
"price": 0.5
}
```

To fetch and store this price from api. I'm defining a struct:
``` rust
pub struct data {
   price: ?
}
``` 
Ques 1: here what would be the type of price?

Here is the code for fetching data:

``` rust
let obj_price = match obj.clone() {
				JsonValue::Object(obj_data) => {
					let (_, v) = obj_data.into_iter().find(|(k, _)| k.iter().copied().eq("price".chars()))?;
					match v {
						JsonValue::Number(val) => val,
						_ => return None,
					}
				},
				_ => return None,
			};

			let Price = obj_price; // ??
```
Ques2: How to convert obj_price to the type that we defined in the struct?

**Comment by xlc** [comment]
You can use FixedU128 from Substrate

You need to do some work to convert NumberValue to it. The logic will be somewhat similar to https://github.com/xlc/lite-json/blob/2c12af4a8606ed3c0988a4b2e9169278df91c6f2/src/json.rs#L36-L39

**Comment by Aideepakchaudhary** [comment]
@xlc Thank you so much for responding!
 First I'm trying to convert the NumberValue to f64 and then convert it into FixedU128:
``` rust
let price = FixedU128::from_float(price_str.to_f64());
```
But I'm getting this error: 
```
let price = FixedU128::from_float(obj_price.to_f64());
      |               ^^^^^^^^^^ function or associated item not found in `FixedU128`

  error[E0599]: no method named `to_f64` found for struct `NumberValue` in the current scope
      |
  640 |             let price = FixedU128::from_float(obj_price.to_f64());
      |                                                         ^^^^^^ method not found in `NumberValue`

```

However I can see both function in the documentation:

<img width="1036" alt="image" src="https://github.com/xlc/lite-json/assets/54492415/945e56f9-10a2-4ab7-82fc-78436c6ef159">



- to_f64() in NumberValue: 
<img width="1073" alt="image" src="https://github.com/xlc/lite-json/assets/54492415/a364e2b1-f0f5-4fa0-a885-4d9807bb8440">

Can you please help me in this?

**Comment by xlc** [comment]
you can’t use float in wasm runtime

**Comment by Aideepakchaudhary** [comment]
@xlc  Then how can i convert NumValue to FixedU128? can you help me in this?

**Comment by Aideepakchaudhary** [comment]
@xlc  Now I'm doing this:
``` rust
let obj_price = match obj.clone() {
				JsonValue::Object(obj_data) => {
					let (_, v) = obj_data.into_iter().find(|(k, _)| k.iter().copied().eq("price".chars()))?;
					match v {
						JsonValue::Number(val) => val,
						_ => return None,
					}
				},
				_ => return None,
};
let bits = obj_price.integer as u128 * 10u128.pow(obj_price.exponent as u32) + u128::from(obj_price.fraction);
// Adjust the bits by multiplying with 10^fractional_length
let adjusted_bits = bits / 10u128.pow(obj_price.fraction_length as u32);

// Create a FixedU128 value from the adjusted bits
let fixed_value = FixedU128::from_rational(adjusted_bits, 10u128.pow(18));
```

But I'm getting `0` in the `fixed_value` instead of `0.5`. 
how can I fix this?

**Comment by xlc** [comment]
you need to convert to FixedU128 at the first step, not the last

closing this as this is unrelated to lite-json

if you have further question, I suggest stackoverflow
